version: '3.8'
services:
  lens-ocr-service:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      # skip node_modules to avoid conflicts
      - /app/node_modules
    restart: always